### ISSUE TITLE
Tracking issue for current very-disruptive API changes

### ISSUE THREAD

**Issue by elidupree** [elidupree/time-steward#44]
Currently, I hesitate to make too many more test cases (and even support libraries) because I'm going to have to update all of them in loads of places when I make API changes.

I'm hoping to settle these ones in particular:

Checklist for "deciding what to do":

- [x] https://github.com/elidupree/time-steward/issues/32, garbage collection (I don't necessarily need to implement garbage collection, just figure out how it will affect the DataHandle API)
- [x] https://github.com/elidupree/time-steward/issues/34, SimpleTimeline interface
- [x] https://github.com/elidupree/time-steward/issues/35, query by reference
- [x] https://github.com/elidupree/time-steward/issues/36, QueryOffset::Before
- [x] https://github.com/elidupree/time-steward/issues/46, StewardData

Checklist for actually implementing it:

- [x] https://github.com/elidupree/time-steward/issues/32, garbage collection
- [x] https://github.com/elidupree/time-steward/issues/34, SimpleTimeline interface
- [x] https://github.com/elidupree/time-steward/issues/35, query by reference
- [x] https://github.com/elidupree/time-steward/issues/36, QueryOffset::Before
- [x] https://github.com/elidupree/time-steward/issues/46, StewardData

**Comment by elidupree** [comment]
With a0c05e5, all these API changes are finished!
